---
- hosts: qa_server
  tasks:
    - name: Clone repository
      git:
        repo: 'https://github.com/cool129/weather_report_nelson.git'
        dest: '/tmp/weather_report_nelson'

    - name: Copy CSV to /tmp
      copy:
        src: '/tmp/weather_report_nelson/Final.report.CSV.csv'
        dest: '/tmp/Final.report.CSV'
        remote_src: yes
